x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile

  image: crypto-market-etl:latest

  env_file:
    - .env

  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor

    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

    AIRFLOW__CORE__FERNET_KEY: ""

    AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"

    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.session

    PYTHONPATH: /opt/project

  volumes:
    - ./dags:/opt/dags
    - ./logs:/opt/logs
    - ./plugins:/opt/plugins
    - ./config:/opt/config

    # Entire project
    - .:/opt/project

  working_dir: /opt/project

  depends_on:
    postgres:
      condition: service_healthy

services:

  postgres:

    image: postgres:16

    container_name: crypto_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:

    <<: *airflow-common

    container_name: airflow_init

    entrypoint: /bin/bash

    command:
      - -c
      - |
        airflow db migrate

        airflow users create \
          --username airflow \
          --password airflow \
          --firstname Abdulmalik \
          --lastname Sanusi \
          --role Admin \
          --email admin@example.com || true

    restart: "no"

  airflow-webserver:

    <<: *airflow-common

    container_name: airflow_webserver

    command: webserver

    restart: unless-stopped

    ports:
      - "8080:8080"

    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:

    <<: *airflow-common

    container_name: airflow_scheduler

    command: scheduler

    restart: unless-stopped

    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:

  postgres_data: